name: "Build and Test"

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
    workflow_dispatch:

jobs:
    unit-tests:
        name: ${{ matrix.framework }} on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        permissions:
            actions: read
            contents: read
        strategy:
            fail-fast: false
            matrix:
                # list all OS and frameworks here, then use "exclude" below to skip some combinations
                # and "include" to add the "sdk_version" mapping
                os: [ubuntu-latest, windows-latest, macos-latest]
                framework: [netcoreapp2.1, netcoreapp3.0, netcoreapp3.1, net5.0, net6.0, net7.0, net8.0, net9.0, net10.0, net48]
                exclude:
                    # net48 only runs on Windows: exclude in from Linux and macOS
                    - os: ubuntu-latest
                      framework: net48
                    - os: macos-latest
                      framework: net48
                    # .NET SDK macOS on arm64 (Apple Silicon) is only supported in net6.0 and above: exclude older frameworks
                    - os: macos-latest
                      framework: netcoreapp2.1
                    - os: macos-latest
                      framework: netcoreapp3.0
                    - os: macos-latest
                      framework: netcoreapp3.1
                    - os: macos-latest
                      framework: net5.0
                # map the target framework (TFM) to the .NET version.
                # we always install and use .NET SDK 10 for building everything, but we also need the matching runtime for running the tests.
                # (we only need the runtimes, not the full SDK, but `actions/setup-dotnet` can only install SDK, which includes the runtime)
                include:
                    - framework: netcoreapp2.1
                      sdk_version: 2.1.x
                    - framework: netcoreapp3.0
                      sdk_version: 3.0.x
                    - framework: netcoreapp3.1
                      sdk_version: 3.1.x
                    - framework: net5.0
                      sdk_version: 5.0.x
                    - framework: net6.0
                      sdk_version: 6.0.x
                    - framework: net7.0
                      sdk_version: 7.0.x
                    - framework: net8.0
                      sdk_version: 8.0.x
                    - framework: net9.0
                      sdk_version: 9.0.x
                    - framework: net10.0
                      sdk_version: 10.0.x
                    - framework: net48
                      sdk_version: 10.0.x

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install libssl on Linux
              # .NET 5.0 and below want libssl v1, which is not available on Ubuntu 24.04 normally
              if: runner.os == 'Linux'
              run: |
                  curl -O https://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.24_amd64.deb
                  sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.24_amd64.deb

            - name: Setup .NET SDK 10.0.x
              # Always install SDK 10.0.x for building
              uses: actions/setup-dotnet@v5
              with:
                  dotnet-version: 10.0.x

            - name: Setup .NET SDK ${{ matrix.sdk_version }}
              # Install the version-specific .NET SDK because need the matching runtime version to run tests
              # (ideally we would install only the runtime, not the full SDK, but `actions/setup-dotnet` can only install SDKs)
              if: matrix.sdk_version != '10.0.x'
              uses: actions/setup-dotnet@v5
              with:
                  dotnet-version: ${{ matrix.sdk_version }}

            - name: Run tests
              run: dotnet test --blame-hang --blame-hang-dump-type none --blame-hang-timeout 60s --framework ${{ matrix.framework }}

    build-nuget:
        name: Build NuGet Package
        runs-on: ubuntu-latest
        permissions:
            actions: read
            contents: read
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup .NET SDK 10.0.x
              uses: actions/setup-dotnet@v5
              with:
                  dotnet-version: 10.0.x

            - name: Build NuGet package
              run: dotnet pack src/StatsdClient/StatsdClient.csproj --configuration Release --output ./nuget-packages

            - name: Upload NuGet package artifact
              uses: actions/upload-artifact@v4
              with:
                  name: nuget-package
                  path: ./nuget-packages/*.nupkg
                  if-no-files-found: error
                  retention-days: 30
