name: "Test"

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    analyze:
        name: Tests (Linux)
        runs-on: ubuntu-latest
        permissions:
            actions: read
            contents: read

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: Setup .NET Core
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: |
                      2.1.x
                      3.0.x
                      3.1.x
                      5.0.x
                      6.0.x
                      7.0.x
                      8.0.x
                      9.0.x
            - name: Run tests
              run: dotnet test tests/StatsdClient.Tests/
